# Generated by Django 3.0.8 on 2020-07-20 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200720_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='is_home',
            new_name='is_hot',
        ),
    ]
