# Generated by Django 3.0.8 on 2020-07-20 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200720_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodscategory',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
